### PR TITLE
Fix placeholder configuration for sample MCVE project

### PR DESCRIPTION
**Pull request by ccjmne**
Hi,

I just used this project to set up a jOOQ MCVE, and noticed two little errors in the sample configuration.
The commits are pretty self-explanatory — expand them for additional information.

Cheers!

### CODE REVIEW

**Comment by lukaseder** [comment]
Very interesting, thanks for your report.

The MCVE works for me on Windows 10. This is the output:

```
lukas@LAPTOP-VH130UJV MINGW64 ~/workspace/playground/jOOQ-mcve (master)
$ mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< org.jooq.trial:jooq-mcve >----------------------
[INFO] Building jOOQ MCVE 1.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/flywaydb/flyway-maven-plugin/5.2.1/flyway-maven-plugin-5.2.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/flywaydb/flyway-maven-plugin/5.2.1/flyway-maven-plugin-5.2.1.pom (4.5 kB at 12 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/flywaydb/flyway-parent/5.2.1/flyway-parent-5.2.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/flywaydb/flyway-parent/5.2.1/flyway-parent-5.2.1.pom (22 kB at 333 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/flywaydb/flyway-maven-plugin/5.2.1/flyway-maven-plugin-5.2.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/flywaydb/flyway-maven-plugin/5.2.1/flyway-maven-plugin-5.2.1.jar (99 kB at 909 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-codegen-maven/3.11.7/jooq-codegen-maven-3.11.7.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-codegen-maven/3.11.7/jooq-codegen-maven-3.11.7.pom (3.5 kB at 71 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-parent/3.11.7/jooq-parent-3.11.7.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-parent/3.11.7/jooq-parent-3.11.7.pom (11 kB at 228 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-codegen-maven/3.11.7/jooq-codegen-maven-3.11.7.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-codegen-maven/3.11.7/jooq-codegen-maven-3.11.7.jar (16 kB at 200 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/jooq/jooq/3.11.7/jooq-3.11.7.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/jooq/jooq/3.11.7/jooq-3.11.7.pom (3.8 kB at 80 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/javax/xml/bind/jaxb-api/2.2.12/jaxb-api-2.2.12.pom
Downloaded from central: https://repo.maven.apache.org/maven2/javax/xml/bind/jaxb-api/2.2.12/jaxb-api-2.2.12.pom (16 kB at 317 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/javax/xml/bind/jaxb-api/2.2.12/jaxb-api-2.2.12.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/jooq/jooq/3.11.7/jooq-3.11.7.jar
Downloaded from central: https://repo.maven.apache.org/maven2/javax/xml/bind/jaxb-api/2.2.12/jaxb-api-2.2.12.jar (102 kB at 448 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/jooq/jooq/3.11.7/jooq-3.11.7.jar (2.4 MB at 7.3 MB/s)
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jooq-mcve ---
[INFO]
[INFO] --- flyway-maven-plugin:5.2.1:migrate (default) @ jooq-mcve ---
Downloading from central: https://repo.maven.apache.org/maven2/org/flywaydb/flyway-core/5.2.1/flyway-core-5.2.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/flywaydb/flyway-core/5.2.1/flyway-core-5.2.1.pom (7.6 kB at 155 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/flywaydb/flyway-core/5.2.1/flyway-core-5.2.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/flywaydb/flyway-core/5.2.1/flyway-core-5.2.1.jar (506 kB at 3.2 MB/s)
[INFO] Flyway Community Edition 5.2.1 by Boxfuse
[INFO] Database: jdbc:h2:~/mcve (H2 1.4)
[INFO] Successfully validated 1 migration (execution time 00:00.009s)
[INFO] Creating Schema History table: "PUBLIC"."flyway_schema_history"
[INFO] Current version of schema "PUBLIC": << Empty Schema >>
[INFO] Migrating schema "PUBLIC" to version 1 - initialise database
[INFO] Successfully applied 1 migration to schema "PUBLIC" (execution time 00:00.038s)
[INFO]
[INFO] --- jooq-codegen-maven:3.11.7:generate (java-generator) @ jooq-mcve ---
Downloading from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-codegen/3.11.7/jooq-codegen-3.11.7.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-codegen/3.11.7/jooq-codegen-3.11.7.pom (1.6 kB at 27 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-meta/3.11.7/jooq-meta-3.11.7.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-meta/3.11.7/jooq-meta-3.11.7.pom (1.4 kB at 30 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-codegen/3.11.7/jooq-codegen-3.11.7.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-meta/3.11.7/jooq-meta-3.11.7.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-codegen/3.11.7/jooq-codegen-3.11.7.jar (149 kB at 592 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/jooq/jooq-meta/3.11.7/jooq-meta-3.11.7.jar (488 kB at 841 kB/s)
[INFO] Database                 : Inferring driver org.h2.Driver from URL jdbc:h2:~/mcve
[INFO] Database                 : Inferring database org.jooq.meta.h2.H2Database from URL jdbc:h2:~/mcve
[INFO] No <inputCatalog/> was provided. Generating ALL available catalogs instead.
[INFO] License parameters
[INFO] ----------------------------------------------------------
[INFO]   Thank you for using jOOQ and jOOQ's code generator
[INFO]
[INFO] Database parameters
[INFO] ----------------------------------------------------------
[INFO]   dialect                : H2
[INFO]   URL                    : jdbc:h2:~/mcve
[INFO]   target dir             : C:\Users\lukas\workspace\playground\jOOQ-mcve\target/generated-sources/jooq-mcve
[INFO]   target package         : org.jooq.mcve
[INFO]   includes               : [.*]
[INFO]   excludes               : []
[INFO]   includeExcludeColumns  : false
[INFO] ----------------------------------------------------------
[INFO]
[INFO] JavaGenerator parameters
[INFO] ----------------------------------------------------------
[INFO]   annotations (generated): false
[INFO]   annotations (JPA: any) : false
[INFO]   annotations (JPA: version):
[INFO]   annotations (validation): false
[INFO]   comments               : true
[INFO]   comments on attributes : true
[INFO]   comments on catalogs   : true
[INFO]   comments on columns    : true
[INFO]   comments on keys       : true
[INFO]   comments on links      : true
[INFO]   comments on packages   : true
[INFO]   comments on parameters : true
[INFO]   comments on queues     : true
[INFO]   comments on routines   : true
[INFO]   comments on schemas    : true
[INFO]   comments on sequences  : true
[INFO]   comments on tables     : true
[INFO]   comments on udts       : true
[INFO]   daos                   : false
[INFO]   deprecated code        : true
[INFO]   global references (any): true
[INFO]   global references (catalogs): true
[INFO]   global references (keys): true
[INFO]   global references (links): true
[INFO]   global references (queues): true
[INFO]   global references (routines): true
[INFO]   global references (schemas): true
[INFO]   global references (sequences): true
[INFO]   global references (tables): true
[INFO]   global references (udts): true
[INFO]   indexes                : true
[INFO]   instance fields        : true
[INFO]   interfaces             : false
[INFO]   interfaces (immutable) : false
[INFO]   javadoc                : true
[INFO]   keys                   : true
[INFO]   links                  : true
[INFO]   pojos                  : false
[INFO]   pojos (immutable)      : false
[INFO]   queues                 : true
[INFO]   records                : true
[INFO]   routines               : true
[INFO]   sequences              : true
[INFO]   table-valued functions : true
[INFO]   tables                 : true
[INFO]   udts                   : true
[INFO]   relations              : true
[INFO] ----------------------------------------------------------
[INFO]
[INFO] Generation remarks
[INFO] ----------------------------------------------------------
[INFO]
[INFO] ----------------------------------------------------------
[INFO] Generating catalogs      : Total: 1
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jooq.tools.reflect.Reflect (file:/C:/Users/lukas/.m2/repository/org/jooq/jooq/3.11.7/jooq-3.11.7.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class)
WARNING: Please consider reporting this to the maintainers of org.jooq.tools.reflect.Reflect
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO]

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.11.7

[INFO] ARRAYs fetched           : 0 (0 included, 0 excluded)
[INFO] Enums fetched            : 0 (0 included, 0 excluded)
[INFO] Packages fetched         : 0 (0 included, 0 excluded)
[INFO] Routines fetched         : 0 (0 included, 0 excluded)
[INFO] Tables fetched           : 1 (1 included, 0 excluded)
[INFO] No schema version is applied for catalog . Regenerating.
[INFO]
[INFO] Generating catalog       : DefaultCatalog.java
[INFO] ==========================================================
[INFO] Generating schemata      : Total: 1
[INFO] No schema version is applied for schema MCVE. Regenerating.
[INFO] Generating schema        : Mcve.java
[INFO] ----------------------------------------------------------
[INFO] Sequences fetched        : 0 (0 included, 0 excluded)
[INFO] UDTs fetched             : 0 (0 included, 0 excluded)
[INFO] Generating tables
[INFO] Synthetic primary keys   : 0 (0 included, 0 excluded)
[INFO] Overriding primary keys  : 1 (0 included, 1 excluded)
[INFO] Generating table         : Test.java [input=TEST, output=TEST, pk=PK_TEST]
[INFO] Indexes fetched          : 1 (1 included, 0 excluded)
[INFO] Tables generated         : Total: 462.072ms
[INFO] Generating table references
[INFO] Table refs generated     : Total: 467.15ms, +5.077ms
[INFO] Generating Keys
[INFO] Keys generated           : Total: 473.557ms, +6.406ms
[INFO] Generating Indexes
[INFO] Indexes generated        : Total: 479.415ms, +5.858ms
[INFO] Generating table records
[INFO] Generating record        : TestRecord.java
[INFO] Table records generated  : Total: 490.98ms, +11.564ms
[INFO] Domains fetched          : 0 (0 included, 0 excluded)
[INFO] Generation finished: MCVE: Total: 491.434ms, +0.454ms
[INFO]
[INFO] Removing excess files
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jooq-mcve ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ jooq-mcve ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to C:\Users\lukas\workspace\playground\jOOQ-mcve\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jooq-mcve ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\lukas\workspace\playground\jOOQ-mcve\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ jooq-mcve ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\Users\lukas\workspace\playground\jOOQ-mcve\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ jooq-mcve ---
[INFO] Surefire report directory: C:\Users\lukas\workspace\playground\jOOQ-mcve\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jooq.mcve.test.MCVETest
2019-05-02 17:24:18,375 main DEBUG Initializing configuration XmlConfiguration[location=C:\Users\lukas\workspace\playground\jOOQ-mcve\target\classes\log4j2.xml]
2019-05-02 17:24:18,382 main DEBUG Installed 1 script engine
Warning: Nashorn engine is planned to be removed from a future JDK release
2019-05-02 17:24:18,575 main DEBUG Oracle Nashorn version: 11.0.1, language: ECMAScript, threading: Not Thread Safe, compile: true, names: [nashorn, Nashorn, js, JS, JavaScript, javascript, ECMAScript, ecmascript], factory class: jdk.nashorn.api.scripting.NashornScriptEngineFactory
2019-05-02 17:24:18,575 main DEBUG PluginManager 'Core' found 116 plugins
2019-05-02 17:24:18,575 main DEBUG PluginManager 'Level' found 0 plugins
2019-05-02 17:24:18,578 main DEBUG PluginManager 'Lookup' found 13 plugins
2019-05-02 17:24:18,579 main DEBUG Building Plugin[name=layout, class=org.apache.logging.log4j.core.layout.PatternLayout].
2019-05-02 17:24:18,584 main DEBUG PluginManager 'TypeConverter' found 26 plugins
2019-05-02 17:24:18,592 main DEBUG PatternLayout$Builder(pattern="%d{ABSOLUTE} %5p [%-50c{4}] - %m%n", PatternSelector=null, Configuration(C:\Users\lukas\workspace\playground\jOOQ-mcve\target\classes\log4j2.xml), Replace=null, charset="null", alwaysWriteExceptions="null", disableAnsi="null", noConsoleNoAnsi="null", header="null", footer="null")
2019-05-02 17:24:18,592 main DEBUG PluginManager 'Converter' found 44 plugins
2019-05-02 17:24:18,593 main DEBUG Building Plugin[name=appender, class=org.apache.logging.log4j.core.appender.ConsoleAppender].
2019-05-02 17:24:18,598 main DEBUG ConsoleAppender$Builder(target="SYSTEM_OUT", follow="null", direct="null", bufferedIo="null", bufferSize="null", immediateFlush="null", ignoreExceptions="null", PatternLayout(%d{ABSOLUTE} %5p [%-50c{4}] - %m%n), name="Console", Configuration(C:\Users\lukas\workspace\playground\jOOQ-mcve\target\classes\log4j2.xml), Filter=null)
2019-05-02 17:24:18,599 main DEBUG Starting OutputStreamManager SYSTEM_OUT.false.false
2019-05-02 17:24:18,599 main DEBUG Building Plugin[name=appenders, class=org.apache.logging.log4j.core.config.AppendersPlugin].
2019-05-02 17:24:18,601 main DEBUG createAppenders(={Console})
2019-05-02 17:24:18,601 main DEBUG Building Plugin[name=AppenderRef, class=org.apache.logging.log4j.core.config.AppenderRef].
2019-05-02 17:24:18,604 main DEBUG createAppenderRef(ref="Console", level="null", Filter=null)
2019-05-02 17:24:18,604 main DEBUG Building Plugin[name=root, class=org.apache.logging.log4j.core.config.LoggerConfig$RootLogger].
2019-05-02 17:24:18,604 main DEBUG createLogger(additivity="null", level="DEBUG", includeLocation="null", ={Console}, ={}, Configuration(C:\Users\lukas\workspace\playground\jOOQ-mcve\target\classes\log4j2.xml), Filter=null)
2019-05-02 17:24:18,606 main DEBUG Building Plugin[name=loggers, class=org.apache.logging.log4j.core.config.LoggersPlugin].
2019-05-02 17:24:18,606 main DEBUG createLoggers(={root})
2019-05-02 17:24:18,607 main DEBUG Configuration XmlConfiguration[location=C:\Users\lukas\workspace\playground\jOOQ-mcve\target\classes\log4j2.xml] initialized
2019-05-02 17:24:18,607 main DEBUG Starting configuration XmlConfiguration[location=C:\Users\lukas\workspace\playground\jOOQ-mcve\target\classes\log4j2.xml]
2019-05-02 17:24:18,607 main DEBUG Started configuration XmlConfiguration[location=C:\Users\lukas\workspace\playground\jOOQ-mcve\target\classes\log4j2.xml] OK.
2019-05-02 17:24:18,608 main DEBUG Shutting down OutputStreamManager SYSTEM_OUT.false.false-1
2019-05-02 17:24:18,608 main DEBUG Shut down OutputStreamManager SYSTEM_OUT.false.false-1, all resources released: true
2019-05-02 17:24:18,608 main DEBUG Appender DefaultConsole-1 stopped with status true
2019-05-02 17:24:18,609 main DEBUG Stopped org.apache.logging.log4j.core.config.DefaultConfiguration@651aed93 OK
2019-05-02 17:24:18,658 main DEBUG Registering MBean org.apache.logging.log4j2:type=6e5e91e4
2019-05-02 17:24:18,661 main DEBUG Registering MBean org.apache.logging.log4j2:type=6e5e91e4,component=StatusLogger
2019-05-02 17:24:18,662 main DEBUG Registering MBean org.apache.logging.log4j2:type=6e5e91e4,component=ContextSelector
2019-05-02 17:24:18,663 main DEBUG Registering MBean org.apache.logging.log4j2:type=6e5e91e4,component=Loggers,name=
2019-05-02 17:24:18,664 main DEBUG Registering MBean org.apache.logging.log4j2:type=6e5e91e4,component=Appenders,name=Console
2019-05-02 17:24:18,665 main DEBUG org.apache.logging.log4j.core.util.SystemClock supports precise timestamps.
2019-05-02 17:24:18,666 main DEBUG Reconfiguration complete for context[name=6e5e91e4] at URI C:\Users\lukas\workspace\playground\jOOQ-mcve\target\classes\log4j2.xml (org.apache.logging.log4j.core.LoggerContext@63f34b70) with optional ClassLoader: null
2019-05-02 17:24:18,666 main DEBUG Shutdown hook enabled. Registering a new one.
2019-05-02 17:24:18,667 main DEBUG LoggerContext[name=6e5e91e4, org.apache.logging.log4j.core.LoggerContext@63f34b70] started OK.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jooq.tools.reflect.Reflect (file:/C:/Users/lukas/.m2/repository/org/jooq/jooq/3.11.7/jooq-3.11.7.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class)
WARNING: Please consider reporting this to the maintainers of org.jooq.tools.reflect.Reflect
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
17:24:18,786  INFO [org.jooq.Constants                                ] -

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.11.7

17:24:18,795 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : insert into "MCVE"."TEST" ("VALUE") values (cast(? as int))
17:24:18,795 DEBUG [org.jooq.tools.LoggerListener                     ] - -> with bind values      : insert into "MCVE"."TEST" ("VALUE") values (42)
17:24:18,809 DEBUG [org.jooq.tools.LoggerListener                     ] - Affected row(s)          : 1
17:24:18,847 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : select "MCVE"."TEST"."ID", "MCVE"."TEST"."VALUE" from "MCVE"."TEST" where "MCVE"."TEST"."ID" = cast(? as int)
17:24:18,848 DEBUG [org.jooq.tools.LoggerListener                     ] - -> with bind values      : select "MCVE"."TEST"."ID", "MCVE"."TEST"."VALUE" from "MCVE"."TEST" where "MCVE"."TEST"."ID" = 1
17:24:18,860 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched result           : +----+-----+
17:24:18,861 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |  ID|VALUE|
17:24:18,861 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +----+-----+
17:24:18,861 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |   1|   42|
17:24:18,861 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +----+-----+
17:24:18,861 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched row(s)           : 1
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.094 sec
2019-05-02 17:24:18,869 pool-1-thread-1 DEBUG Stopping LoggerContext[name=6e5e91e4, org.apache.logging.log4j.core.LoggerContext@63f34b70]
2019-05-02 17:24:18,870 pool-1-thread-1 DEBUG Stopping LoggerContext[name=6e5e91e4, org.apache.logging.log4j.core.LoggerContext@63f34b70]...
2019-05-02 17:24:18,871 pool-1-thread-1 DEBUG Shutting down OutputStreamManager SYSTEM_OUT.false.false
2019-05-02 17:24:18,871 pool-1-thread-1 DEBUG Shut down OutputStreamManager SYSTEM_OUT.false.false, all resources released: true
2019-05-02 17:24:18,872 pool-1-thread-1 DEBUG Appender Console stopped with status true
2019-05-02 17:24:18,872 pool-1-thread-1 DEBUG Stopped XmlConfiguration[location=C:\Users\lukas\workspace\playground\jOOQ-mcve\target\classes\log4j2.xml] OK
2019-05-02 17:24:18,872 pool-1-thread-1 DEBUG Stopped LoggerContext[name=6e5e91e4, org.apache.logging.log4j.core.LoggerContext@63f34b70] with status true

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ jooq-mcve ---
[INFO] Building jar: C:\Users\lukas\workspace\playground\jOOQ-mcve\target\jooq-mcve-1.0.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jooq-mcve ---
[INFO] Installing C:\Users\lukas\workspace\playground\jOOQ-mcve\target\jooq-mcve-1.0.jar to C:\Users\lukas\.m2\repository\org\jooq\trial\jooq-mcve\1.0\jooq-mcve-1.0.jar
[INFO] Installing C:\Users\lukas\workspace\playground\jOOQ-mcve\pom.xml to C:\Users\lukas\.m2\repository\org\jooq\trial\jooq-mcve\1.0\jooq-mcve-1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.369 s
[INFO] Finished at: 2019-05-02T17:24:19+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by lukaseder** [comment]
Having said so, I agree with this change, this would probably work on more RDBMS than just H2:
https://github.com/jOOQ/jOOQ-mcve/pull/2/commits/cf840ae00d2b5b85cde9e18839cc0bc03e3d6c04

I don't agree with this change (for H2):
https://github.com/jOOQ/jOOQ-mcve/pull/2/commits/ca9781074cda5f4df133aaf6d7fa3d7881e628af

But I understand you probably ran the MCVE on PostgreSQL, in case of which the schema name would indeed be lower case.

I'll merge your PR and add an additional `<inputSchema>`, so we have both cases.

**Comment by lukaseder** [comment]
Applied this fix on top of yours:
https://github.com/jOOQ/jOOQ-mcve/commit/23e9a6322dd04e0a2455a5acb3e3674e3251a5ba

**Comment by ccjmne** [comment]
You are right, I did run it all against a PostgreSQL database.

I checked for the `DROP SCHEMA [IF EXISTS] {name}` syntax for MySQL and PostgreSQL, I googled for the equivalent in H2 but couldn't find the right piece of doc in the first 30 seconds and I gave up 😶

About the schema name, the only (mild) annoyance was that the build would "succeed" but not generate any code (although there would be a warning somewhere in the output that would let me know that I had to double-check for the `<inputSchema>` property that is case-sensitive).

Anyways, thanks for the follow-up!
And for jOOQ 👍

**Pull request merged**
